server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autoservice_dev
    username: autoservice_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # схема уже есть в БД, просто проверяем соответствие
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
